### ISSUE TITLE
error handling on update/redeploy of a plugin

### ISSUE THREAD

**Issue by jangalinski** [AxonIQ/axon-server-plugin-api#8]
From #7, quote @MGathier : "Unfortunately, at this point nothing is reported or logged, so we should improve on this"

Setup:

* provide a plugin that throws an exception in Activator#start()
* upload first time: exception on cli and server log
* upload second time: success

Expected behavior:

* exception every time

**Comment by lfgcampos** [comment]
I believe this one will be fixed by https://github.com/AxonIQ/axon-server-se/pull/331.
But I will wait for @MGathier to double check it.

**Comment by MGathier** [comment]
This is indeed addresses in the PR which Lucas was referring to.  Today we have released Axon Server SE 4.5.5 which includes this fix. In this release we have also increased the default values for the maximum file size and request size for multipart requests to 25MB.

**Comment by lfgcampos** [comment]
As mentioned before, this is fixed and the fix is on Axon Server SE 4.5.5.
